services:
  flask-dummy:
    build: ./flask-dummy
    container_name: flask-dummy
    ports:
      - "8080:8080"

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    ports:
      - "4317:4317"
    command: >
      run --server.http.listen-addr=0.0.0.0:4317 --storage.path=/var/lib/alloy/data
      /etc/alloy/config.alloy

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki:/mnt/config
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yaml

  # promtail:
  #   image: grafana/promtail:latest
  #   container_name: promtail
  #   volumes:
  #     - ./loki:/mnt/config
  #     - /var/log:/var/log
  #   ports:
  #     - "9080:9080"
  #   depends_on:
  #     - loki
  #   command: -config.file=/mnt/config/promtail-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./loki-dashboard.json:/var/lib/grafana/dashboards/loki-dashboard.json
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"

volumes:
  grafana-storage:
